apiVersion: v1
kind: Service
metadata:
  name: fintech-secure-lab-service
spec:
  selector:
    app: fintech-secure-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
